/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { QACategory, FeedbackChannel, FeedbackStatus, QAEntry, FeedbackEntry } from './types';

export const MOCK_QA: QAEntry[] = [
  {
    id: 'Q-001',
    category: QACategory.PRE_SALES,
    question: '你们这个屏幕分辨率是多少？刷新率高不高？',
    script: '您好！MagicFrame 采用的是特别定制的**“防眩光纸质感画屏”**，它和普通的平板完全不同。我们摒弃了刺眼的电子光，配合独家调校的 3000K 晨曦暖白环境灯，能极其逼真地还原油画的笔触。它的设计初衷是为了像一幅真实的艺术品一样，无感、静谧地融入您的家居环境中。',
    notes: '绝对不要提具体的 2K/4K 或 60Hz 等参数，立刻把话题转移到防眩光和纸质感上。',
    updated_at: 1710720000000,
  },
  {
    id: 'Q-002',
    category: QACategory.PRE_SALES,
    question: '这个画框是插电的还是充电的？电源线露在外面是不是很难看？',
    script: '为了保证 AI 算力和画廊的常亮体验，画框是需要插电使用的哦。为了墙面美观，如果您是挂在已装修好的墙面，我们随箱赠送了与墙面颜色极度融合的“隐形超细电源线”，并配有理线器，挂在墙上几乎是可以忽略不计的呢。',
    notes: '必须诚实告知需要插电。重点强调隐形线材。',
    updated_at: 1710720000000,
  },
  {
    id: 'Q-003',
    category: QACategory.CORE_FEATURES,
    question: 'AI 修复老照片功能会不会泄露我父母的隐私？',
    script: '请您放一万个心！您上传的家庭照片仅用于本次 AI 修复计算，修复完成后即刻进行金融级加密存储，绝不会被用于任何外部训练。',
    notes: '打消长辈对AI的顾虑，强调端到端隐私保护。',
    updated_at: 1710720000000,
  },
  {
    id: 'Q-004',
    category: QACategory.CORE_FEATURES,
    question: '我想给家里老人买，但他们不会下载 App 怎么办？',
    script: '这正是 MagicFrame 最大的心意！爷爷奶奶完全不需要下载任何 App。您绑定画框后，长辈只要用微信扫一扫屏幕上的二维码，就能进入极简小程序，按住就能说话留便利贴，就像发微信语音一样简单！',
    notes: '放大零门槛交互这个超级卖点，切中送礼人群痛点。',
    updated_at: 1710720000000,
  },
  {
    id: 'Q-005',
    category: QACategory.ART_CONTENT,
    question: '里面那些莫奈、梵高的画，以后会收费吗？',
    script: '画框内置的美学空间（包含莫奈、梵高、达芬奇等海量世界顶级公版名画）是终身免费为您开放的！您可以随时根据家里的氛围自动轮播，基础的古典艺术享受永远免费。',
    notes: '明确公版免费。如果有追问，再提未来可能有现代艺术家的付费联名款。',
    updated_at: 1710720000000,
  },
  {
    id: 'Q-006',
    category: QACategory.ART_CONTENT,
    question: '除了名画，我可以上传自己手机里拍的风景照吗？',
    script: '当然可以！MagicFrame 不仅是世界级的美术馆，更是您的私人画廊。您不仅可以上传原图，还能使用画框的AI风格化魔法，把您拍的普通风景照，一键变成油画或水墨画风格展示出来哦！',
    notes: '顺便种草AI变艺术风格这个功能。',
    updated_at: 1710720000000,
  },
  {
    id: 'Q-007',
    category: QACategory.AFTER_SALES,
    question: '为什么画框突然黑屏了？是不是坏了？',
    script: '您先别着急！为了保护睡眠和节约用电，它内置了智能感应器。如果您长时间不在画框前走动，它会自动进入深睡黑屏模式。您试着在画框前走动一下，看看它是不是又像魔法一样亮起来了呢？',
    notes: '安抚情绪，用智能省电的逻辑解释雷达休眠机制。',
    updated_at: 1710720000000,
  },
  {
    id: 'Q-008',
    category: QACategory.AFTER_SALES,
    question: 'AI生成图片时，等了10秒还没出来，太慢了吧？',
    script: '非常抱歉让您久等了！因为画框正在为您进行极高精度的殿堂级笔触重构，为了保证出来的画面在纸质屏上足够惊艳，AI 画师需要一点点时间精雕细琢。您可以一边欣赏画框的氛围灯效一边稍作等待哦。',
    notes: '不要解释网络延迟或服务器拥挤，包装成慢工出细活的艺术品味。',
    updated_at: 1710720000000,
  },
];

export const MOCK_FEEDBACK: FeedbackEntry[] = [
  {
    recordId: 'mock-1',
    id: 'F-001',
    user_voice: '这个画框能不能放我自己拍的视频啊？',
    category: QACategory.CORE_FEATURES,
    channel: FeedbackChannel.XHS,
    image_urls: [],
    status: FeedbackStatus.PENDING,
    submitter: 'D',
    created_at: 1710720000000,
  },
  {
    recordId: 'mock-2',
    id: 'F-002',
    user_voice: '木色边框什么时候能出？我家是侘寂风，黑白色都不太搭。',
    category: QACategory.APPEARANCE,
    channel: FeedbackChannel.XHS,
    image_urls: [],
    status: FeedbackStatus.PROCESSING,
    submitter: 'D',
    created_at: 1710720000000,
  },
  {
    recordId: 'mock-3',
    id: 'F-003',
    user_voice: '修复我奶奶的老照片时，脸部有一点点变形，这个能手动微调吗？',
    category: QACategory.CORE_FEATURES,
    channel: FeedbackChannel.XHS,
    image_urls: [],
    status: FeedbackStatus.PENDING,
    submitter: 'D',
    created_at: 1710720000000,
  },
  {
    recordId: 'mock-4',
    id: 'F-004',
    user_voice: '苹果手机的 iCloud 相册能不能直接同步过来？',
    category: QACategory.CORE_FEATURES,
    channel: FeedbackChannel.DY,
    image_urls: [],
    status: FeedbackStatus.RESOLVED,
    submitter: 'D',
    created_at: 1710720000000,
  },
  {
    recordId: 'mock-5',
    id: 'F-005',
    user_voice: '晚上的红外人感好像不太灵敏，我走过去有时候不亮。',
    category: QACategory.AFTER_SALES,
    channel: FeedbackChannel.DY,
    image_urls: [],
    status: FeedbackStatus.PENDING,
    submitter: 'D',
    created_at: 1710720000000,
  },
  {
    recordId: 'mock-6',
    id: 'F-006',
    user_voice: '可以几个人同时绑定一个画框吗？我和我老婆都想发便利贴。',
    category: QACategory.CORE_FEATURES,
    channel: FeedbackChannel.XHS,
    image_urls: [],
    status: FeedbackStatus.PROCESSING,
    submitter: 'D',
    created_at: 1710720000000,
  },
  {
    recordId: 'mock-7',
    id: 'F-007',
    user_voice: '画框播放画作的时候，能顺便当蓝牙音箱放点背景音乐吗？',
    category: QACategory.CORE_FEATURES,
    channel: FeedbackChannel.XHS,
    image_urls: [],
    status: FeedbackStatus.PENDING,
    submitter: 'D',
    created_at: 1710720000000,
  },
  {
    recordId: 'mock-8',
    id: 'F-008',
    user_voice: '保修期是多久？有没有类似 AppleCare 那种碎屏险可以买？',
    category: QACategory.AFTER_SALES,
    channel: FeedbackChannel.DY,
    image_urls: [],
    status: FeedbackStatus.PENDING,
    submitter: 'D',
    created_at: 1710720000000,
  },
  {
    recordId: 'mock-9',
    id: 'F-009',
    user_voice: '极简风的几何色块画作太少了，之后会更新蒙德里安风格的库吗？',
    category: QACategory.ART_CONTENT,
    channel: FeedbackChannel.XHS,
    image_urls: [],
    status: FeedbackStatus.PROCESSING,
    submitter: 'D',
    created_at: 1710720000000,
  },
];
